# version: '3.8'

services:
  redis-1:
    restart: unless-stopped
    container_name: redis74
    image: docker.1ms.run/redis:7.4.3
    ports:
      - "6379:6379"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/redis/data:/data
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/redis/logs:/var/log/redis
    environment:
      - TZ=Asia/Shanghai
    command: redis-server --appendonly yes --loglevel warning
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1'      # 最多 1 核
          memory: 512M   # 最多 512MB
        reservations:
          memory: 256M  # 尽量保证 256MB
    networks:
      - hadoop-redis-net

networks:
  hadoop-redis-net:
    driver: bridge
    attachable: true