services:
  dpanel:
    image: docker.1ms.run/dpanel/dpanel:latest
    container_name: dpanel # 更改此名称后，请同步修改下方 APP_NAME 环境变量
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8807:8080 # 替换 8807 可更改面板访问端口
    environment:
      APP_NAME: dpanel # 请保持此名称与 container_name 一致
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/dpanel/docker.sock:/var/run/docker.sock
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/dpanel:/dpanel
    networks:
      - dpanel-net

networks:
  dpanel-net:
    driver: bridge
    attachable: true