# version: '3.8'

services:
  nginx:
    restart: unless-stopped
    container_name: nginx
    image: docker.1ms.run/nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./volumes/nginx/conf.d:/etc/nginx/conf.d
      - ./volumes/nginx/html:/usr/share/nginx/html
      - ./volumes/nginx/log:/var/log/nginx
      - ./volumes/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./volumes/nginx/certs:/etc/nginx/certs:ro
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true
    networks:
      - nginx_net

networks:
  nginx_net:
    driver: bridge
    attachable: true